os: linux
language: c
arch: amd64

notifications:
  email: false

before_install:
    - cd kernel/
    - ./install_SGX_driver.sh
    - make clean load

install:
    - cd sdk/intel-sdk/
    - ./install_SGX_SDK.sh
    - source /opt/intel/sgxsdk/environment
    - sudo service aesmd status

jobs:
    include:
       - dist: bionic   # 18.04
       - dist: focal    # 20.04
